name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    # Checkout the repository and submodules
    - name: Checkout code and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive # Ensures submodules are fetched
        fetch-depth: 0        # Ensures the full history is fetched

    # Log in to GitHub Container Registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and push the Docker image
    - name: Build and Push Docker Image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/bossboxing/friendblockly:latest
        docker push ghcr.io/bossboxing/friendblockly:latest